CREATE TABLE item
(iID  	INTEGER,
itemY 	INTEGER,
itemP 	INTEGER,
itemT   VARCHAR,
PRIMARY KEY(iID),
);

CREATE TABLE CD
(cdID 		INTEGER,
subject 	VARCHAR(15),
COMPOSER	VARCHAR(15)	NOT NULL,
ARTIST		VARCHAR(15)	NOT NULL,
PRODUCER	VARCHAR(15)	NOT NULL,
FOREIGN KEY(CD_ITEMID) REFERENCES ITEM(ITEMID),
);

CREATE TABLE BOOK
(boodID			INTEGER,	
ISDN			CHAR(13)	NOT NULL,
edition			INTEGER,
author			VARCHAR(15)	NOT NULL,
editor			VARCHAR,
FOREIGN KEY(BOOOK_ITEMID) REFERENCES ITEM(ITEMID),
);

CREATE TABLE customer
(cNAME	VARCHAR(15)	NOT NULL,
cID		INTEGER NOT NULL,
state		VARCHAR(2),
street		VARCHAR,
zip		VARCHAR,
city		VARCHAR,
PRIMARY KEY(CUSOMTERID),
);

CREATE TABLE employee
(EMPLOYEE_NAME	VARCHAR(15)	NOT NULL,
SALARY	INTEGER,	
PHONE	CHAR(9)	
JOBTITLE	VARCHAR	NOT NULL,
PAYLEVEL	INTEGER,
eID	CHAR(9)	NOT NULL,
PRIMARY KEY(EMPLOYEEID),
);

CREATE TABLE sells
(eID	INTEGER	NOT NULL,
cID	INTEGER	NOT NULL,
sID	INTEGER	NOT NULL,
itemID	INTEGER	NOT NULL,
itemQ	INTEGER	NOT NULL,
vID	INTEGER NOT NULL,
PRIMARY KEY(sID),
FOREIGN KEY(eID) REFERENCES EMPLOYEE(eID),
FOREIGN KEY(cID) REFERENCES CUSTOMER(cID),
FOREIGN KEY(itemID) REFERENCES CUSTOMER(itemID),
);

CREATE TABLE VENDOR
(vNAME	VARCHAR(15)	NOT NULL,
vAdd	VARCHAR(15)	NOT NULL,
PERSON	VARCHAR(15)	NOT NULL,
PHONE	CHAR(9)	NOT NULL,
VID	INTEGER	NOT NULL,
PRIMARY KEY(VENDORID),
);

CREATE TABLE ORDER
(oID	INTEGER,
vID	INTEGER,
oDate	VARCHAR,
itemID	INTEGER,
itemQ	LONG,
PRIMARY KEY(oID),
FOREIGN	KEY(itemID) REFERENCES item(iID),
);