CREATE TABLE EMPLOYEE
(EMPLOYEE_NAME	VARCHAR(15)	NOT NULL,
SALARY	DECIMAL(10,2),	长度只能是一个整数值（10）
PHONE	CHAR(9)	
JOBTITLE	VARCHAR(15)	NOT NULL,
PAYLEVEL	INTEGER,
EMPLOYEEID	CHAR(9)	NOT NULL,
PRIMARY KEY(EMPLOYEEID),
);

CREATE TABLE SELLS
(SELLS_EID	CHAR(9)	NOT NULL,
SELLS_CID	CHAR(9)	NOT NULL,
SELLS_SID	CHAR(9)	NOT NULL,
FOREIGN KEY(SELLS_EID) REFERENCES EMPLOYEE(EMPLOYEEID),
FOREIGN KEY(SELLS_CID) REFERENCES CUSTOMER(CUSTOMERID),
FOREIGN KEY(SELLS_SID) REFERENCES SALE(SALEID),
);

CREATE TABLE CUSOMTER
(CUSOMTER_NAME	VARCHAR(15)	NOT NULL,
CUSOMTERID	CHAR(9)	NOT NULL,
PRIMARY KEY(CUSOMTERID),
);

CREATE TABLE ADDRESS
(STATE	CHAR(2)		state可以null而zip不能null？
ZIP	INTEGER	NOT NULL,
CITY	VARCHAR(15)	NOT NULL,
STREET	VARCHAR(15)	NOT NULL,
ADDR_CID	CHAR(9)	NOT NULL,
FOREIGN KEY(ADDR_CID) REFERENCES	CUSTOMER(CUSOMTERID),
);

CREATE TABLE SALE
(SDATE	DATE,
SALEID	CHAR(9)	NOT NULL,
PRIMARY KEY(SALEID),
);

CREATE TABLE ITEM	为什么item和sale表一样？
(SDATE	DATE,
SALEID	CHAR(9)	NOT NULL,
PRIMARY KEY(SALEID),
);

CREATE TABLE HAS
(HAS_ITEMID	CHAR(9)	NOT NULL,
HAS_SALEID	CHAR(9)	NOT NULL,
SAPCE	INTEGER	NOT NULL,		这是space还是aspce？
SQUANTITY	INTEGER NOT NULL,
FOREIGN KEY(HAS_ITEMID) REFERENCES ITEM(ITEMID),
FOREIGN KEY(HAS_SALEID) REFERENCES SALE(SALEID),
);

CREATE TABLE VENDOR
(VENDORNAME	VARCHAR(15)	NOT NULL,
VENDORADDR	VARCHAR(15)	NOT NULL,
CONTPERSON	VARCHAR(15)	NOT NULL,
VENDORPHONE	CHAR(9)	NOT NULL,
VENDORID	CHAR(9)	NOT NULL,
PRIMARY KEY(VENDORID),
);

CREATE TABLE ITEM				应该有一个title的？
(ITEMPRICE		INTEGER NOT NULL,	price一定是integer吗？
ITEMID			CHAR(9)	NOT NULL,
YEARS			CHAR(4)	NOT NULL,
QUANTITYINSTOCK	INTEGER	NOT NULL,		建议改成QINS
PRIMARY KEY(ITEMID),
);

CREATE TABLE CD
(MUSSUBJECT	VARCHAR(15),
COMPOSER	VARCHAR(15)	NOT NULL,
ARTIST		VARCHAR(15)	NOT NULL,
PRODUCER	VARCHAR(15)	NOT NULL,
CD_ITEMID	CHAR(9),
FOREIGN KEY(CD_ITEMID) REFERENCES ITEM(ITEMID),
);

CREATE TABLE BOOK
(ISDN			CHAR(13)	NOT NULL,
YEARS			CHAR(4)	NOT NULL,
EDITION			INTEGER,
AUTHOR			VARCHAR(15)	NOT NULL,
EDITOR			VARCHAR(15),
BOOOK_ITEMID	CHAR(9)	NOT NULL,		我猜多打了一个O
FOREIGN KEY(BOOOK_ITEMID) REFERENCES ITEM(ITEMID),
);

CREATE TABLE ORDERS
(ODATE			DATE NOT NULL,
ORDERID			CHAR(9)	NOT NULL,
ORDER_VENDORID	CHAR(9)	NOT NULL,
PRIMARY KEY(ORDERID),
FOREIGN	KEY(ORDER_VENDORID) REFERENCES VENDOR(VENDORID),
);

CREATE TABLE CONTAIN
(CONTAIN_ORDERID	CHAR(9) NOT NULL,
CONTAIN_VENDORID	CHAR(9)	NOT NULL,
OQUANTITY			INTEGER	NOT NULL,
OPRICE				INTEGER NOT NULL,
FOREIGN	KEY(CONTAIN_ORDERID)  REFERENCES ORDERS(ORDERID),
FOREIGN	KEY(CONTAIN_VENDORID) REFERENCES VENDOR(VENDORID),
);